//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireBreath.UsersMicroservice.Translations {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation_UsersRoles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation_UsersRoles() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FireBreath.UsersMicroservice.Translations.Translation_UsersRoles", typeof(Translation_UsersRoles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a And.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id not found.
        /// </summary>
        public static string ID_no_found_description {
            get {
                return ResourceManager.GetString("ID_no_found_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You don&apos;t have permission to create/update a user.
        /// </summary>
        public static string No_permission {
            get {
                return ResourceManager.GetString("No_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email is not available.
        /// </summary>
        public static string NotAvailable_Email {
            get {
                return ResourceManager.GetString("NotAvailable_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username is not available.
        /// </summary>
        public static string NotAvailable_Username {
            get {
                return ResourceManager.GetString("NotAvailable_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        public static string Passwords_donot_match {
            get {
                return ResourceManager.GetString("Passwords_donot_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role is non existing.
        /// </summary>
        public static string Role_no_exists {
            get {
                return ResourceManager.GetString("Role_no_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error setting image.
        /// </summary>
        public static string Setting_image_error {
            get {
                return ResourceManager.GetString("Setting_image_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating password.
        /// </summary>
        public static string Update_password_error {
            get {
                return ResourceManager.GetString("Update_password_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating role.
        /// </summary>
        public static string Update_role_error {
            get {
                return ResourceManager.GetString("Update_role_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access not allowed.
        /// </summary>
        public static string User_access_not_allowed {
            get {
                return ResourceManager.GetString("User_access_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user has been deleted.
        /// </summary>
        public static string User_hasbeen_deleted {
            get {
                return ResourceManager.GetString("User_hasbeen_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user is locked.
        /// </summary>
        public static string User_locked_message {
            get {
                return ResourceManager.GetString("User_locked_message", resourceCulture);
            }
        }
    }
}
